// <auto-generated />
using ArcheCore.PersistenceServer.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArcheCore.Server.Persistence.Migrations
{
    [DbContext(typeof(PersistenceDbContext))]
    [Migration("20260924181832_GeneralMailbox")]
    partial class GeneralMailbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ArcheCore.PersistenceServer.Api.Models.AccountCredits", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<int>("Balance")
                        .HasColumnType("int")
                        .HasColumnName("balance");

                    b.Property<long>("UpdatedAtTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_at_ticks");

                    b.HasKey("AccountId");

                    b.ToTable("account_credits", (string)null);
                });

            modelBuilder.Entity("ArcheCore.PersistenceServer.Api.Models.CashShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("category");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsGiftable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_giftable");

                    b.Property<int>("ItemTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("item_template_id");

                    b.Property<int>("PriceCredits")
                        .HasColumnType("int")
                        .HasColumnName("price_credits");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.ToTable("cash_shop_items", (string)null);
                });

            modelBuilder.Entity("ArcheCore.PersistenceServer.Api.Models.Character", b =>
                {
                    b.Property<long>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("character_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("CharacterId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<int>("Gold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("gold");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<float>("PosX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("pos_x");

                    b.Property<float>("PosY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(2f)
                        .HasColumnName("pos_y");

                    b.Property<float>("PosZ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("pos_z");

                    b.HasKey("CharacterId");

                    b.HasIndex("AccountId");

                    b.ToTable("characters", null, t =>
                        {
                            t.HasCheckConstraint("CK_characters_gold_nonnegative", "gold >= 0");
                        });
                });

            modelBuilder.Entity("ArcheCore.PersistenceServer.Api.Models.CharacterInventoryItem", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("character_id");

                    b.Property<int>("Slot")
                        .HasColumnType("int")
                        .HasColumnName("slot");

                    b.Property<int>("ItemTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("item_template_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("CharacterId", "Slot");

                    b.ToTable("character_inventory", null, t =>
                        {
                            t.HasCheckConstraint("CK_character_inventory_item_positive", "item_template_id > 0 AND quantity > 0");
                        });
                });

            modelBuilder.Entity("ArcheCore.PersistenceServer.Api.Models.CharacterQuest", b =>
                {
                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("character_id");

                    b.Property<int>("QuestId")
                        .HasColumnType("int")
                        .HasColumnName("quest_id");

                    b.Property<string>("Progress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("progress");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("status");

                    b.HasKey("CharacterId", "QuestId");

                    b.HasIndex("CharacterId");

                    b.ToTable("character_quests", (string)null);
                });

            modelBuilder.Entity("ArcheCore.PersistenceServer.Api.Models.Mail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("character_id");

                    b.Property<long>("CreatedAtTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at_ticks");

                    b.Property<int>("Gold")
                        .HasColumnType("int")
                        .HasColumnName("gold");

                    b.Property<int>("ItemQuantity")
                        .HasColumnType("int")
                        .HasColumnName("item_quantity");

                    b.Property<int>("ItemTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("item_template_id");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sender");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("subject");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("mail", (string)null);
                });

            modelBuilder.Entity("ArcheCore.PersistenceServer.Api.Models.MailReceipt", b =>
                {
                    b.Property<string>("DeliveryKey")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("delivery_key");

                    b.Property<long>("CreatedAtTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("created_at_ticks");

                    b.HasKey("DeliveryKey");

                    b.ToTable("mail_receipts", (string)null);
                });

            modelBuilder.Entity("ArcheCore.PersistenceServer.Api.Models.CharacterInventoryItem", b =>
                {
                    b.HasOne("ArcheCore.PersistenceServer.Api.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
