<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="LiteNetLib" Version="2.1.4" />
      <PackageReference Include="MessagePack" Version="3.1.7" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.0" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="11.0.0-preview.5.26302.115" />
      <PackageReference Include="MoonSharp" Version="2.0.0" />
      <PackageReference Include="NLog" Version="6.1.3" />
      <PackageReference Include="NLog.Extensions.Logging" Version="6.1.3" />
      <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Core\Lua\DeveloperSDK\" />
      <Folder Include="Core\Network\" />
      <Folder Include="Core\Packets\W2CSenders\" />
      <Folder Include="Physics\" />
      <Folder Include="Services\" />
      <Folder Include="Utils\Database\MySQL\" />
    </ItemGroup>

    <ItemGroup>
      <None Update="nlog.config">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
        <None Update="Data\**\*">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ArcheCore.Net\ArcheCore.Net.csproj" />
    </ItemGroup>

</Project>
