using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using NLog;
using ArcheCore.Server.World.GameData.Npcs;
using ArcheCore.Server.World.Utils.Database.SQLite;

namespace ArcheCore.Server.World.Utils.Database.SQLite;

/// <summary>
/// Replaces GameDataPatchRunner's INSERT-only patches (007, 010, 023 —
/// the ones tagged "Auto-generated by ArcheCore NPC Spawner Exporter" /
/// "ArcheCore Dev Tools") with an idempotent, EF-based upsert from plain
/// JSON files. This is the designer-facing seam: a non-programmer (or a
/// Unity editor export tool) edits/regenerates GameData/Content/*.json,
/// nobody writes SQL or touches a migration.
///
/// Schema still comes entirely from EF migrations (WorldDataDbContext +
/// Migrations/) — this class only ever reads/writes rows through DbSet,
/// never DDL. Call SeedAsync() once at boot, after
/// WorldDataDbContext.Database.MigrateAsync() has run.
/// </summary>
public class GameContentSeeder
{
    private static readonly Logger Logger = LogManager.GetCurrentClassLogger();

    private readonly IDbContextFactory<WorldDataDbContext> _dbFactory;
    private readonly string _contentDir;

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true
    };

    public GameContentSeeder(IDbContextFactory<WorldDataDbContext> dbFactory)
    {
        _dbFactory = dbFactory;

        // Sits next to Lua/Server and SQL/patches in the output dir —
        // same "relative to the built exe" convention LuaEngine already
        // uses for PlayerManager.Lua.
        _contentDir = Path.Combine(AppContext.BaseDirectory, "GameData", "Content");
    }

    public async Task SeedAsync()
    {
        if (!Directory.Exists(_contentDir))
        {
            Logger.Warn($"[ContentSeeder] Content directory not found, skipping: {_contentDir}");
            return;
        }

        await using var db = await _dbFactory.CreateDbContextAsync();

        await SeedNpcTemplatesAsync(db);
        await SeedNpcSpawnersAsync(db);

        await db.SaveChangesAsync();
    }

    private record NpcTemplateRecord(string Name, int Level, string ModelType, float InteractRange);

    private async Task SeedNpcTemplatesAsync(WorldDataDbContext db)
    {
        var path = Path.Combine(_contentDir, "npc_templates.json");
        if (!File.Exists(path))
        {
            Logger.Info($"[ContentSeeder] No npc_templates.json found, skipping ({path}).");
            return;
        }

        var records = JsonSerializer.Deserialize<List<NpcTemplateRecord>>(
            await File.ReadAllTextAsync(path), JsonOptions) ?? new();

        int added = 0, updated = 0;

        foreach (var r in records)
        {
            // Name is the natural key here - two designers exporting the
            // same NPC shouldn't create duplicate rows. If you need two
            // NPCs with the same display name, add an explicit Key field
            // to the JSON/table rather than relying on Name uniqueness.
            var existing = await db.NpcTemplates.FirstOrDefaultAsync(t => t.Name == r.Name);

            if (existing == null)
            {
                db.NpcTemplates.Add(new NpcTemplate
                {
                    Name = r.Name,
                    Level = r.Level,
                    ModelType = r.ModelType,
                    InteractRange = r.InteractRange
                });
                added++;
            }
            else
            {
                existing.Level = r.Level;
                existing.ModelType = r.ModelType;
                existing.InteractRange = r.InteractRange;
                updated++;
            }
        }

        Logger.Info($"[ContentSeeder] NpcTemplates: {added} added, {updated} updated from {path}.");
    }

    private record NpcSpawnerRecord(int TemplateId, float X, float Y, float Z, int Count, float Radius);

    private async Task SeedNpcSpawnersAsync(WorldDataDbContext db)
    {
        var path = Path.Combine(_contentDir, "npc_spawners.json");
        if (!File.Exists(path))
        {
            Logger.Info($"[ContentSeeder] No npc_spawners.json found, skipping ({path}).");
            return;
        }

        var records = JsonSerializer.Deserialize<List<NpcSpawnerRecord>>(
            await File.ReadAllTextAsync(path), JsonOptions) ?? new();

        int added = 0, updated = 0;

        foreach (var r in records)
        {
            // Spawners have no natural display name, so the key is
            // (TemplateId, position). Two spawners of the same template
            // at the same exact position would collide - if that's ever
            // a real case, add an explicit Id/Key to the JSON instead.
            var existing = await db.NpcSpawners.FirstOrDefaultAsync(s =>
                s.TemplateId == r.TemplateId && s.X == r.X && s.Y == r.Y && s.Z == r.Z);

            if (existing == null)
            {
                db.NpcSpawners.Add(new NpcSpawnerTable
                {
                    TemplateId = r.TemplateId,
                    X = r.X,
                    Y = r.Y,
                    Z = r.Z,
                    Count = r.Count,
                    Radius = r.Radius
                });
                added++;
            }
            else
            {
                existing.Count = r.Count;
                existing.Radius = r.Radius;
                updated++;
            }
        }

        Logger.Info($"[ContentSeeder] NpcSpawners: {added} added, {updated} updated from {path}.");
    }
}