-- Auto-generated by ArcheCore NPC Spawner Exporter
-- Scene: main_world
-- Date: 2026-06-28 03:58

-- Orc Grunt x6 (Template 1)
INSERT INTO "NpcSpawners" (TemplateId, X, Y, Z, Count, Radius) VALUES (1, -13.8750, 1.2600, 9.8100, 6, 6.0);

