-- Auto-generated by ArcheCore Dev Tools
-- Scene: main_world
-- Date:  2026-06-28 05:31

-- Elven Invaders x2 (TemplateId=123)
INSERT INTO "NpcSpawners" (TemplateId, X, Y, Z, Count, Radius) VALUES (123, 10.0500, 0.0000, 0.0000, 2, 12.0);

-- Crimson Army x5 (TemplateId=23)
INSERT INTO "NpcSpawners" (TemplateId, X, Y, Z, Count, Radius) VALUES (23, -10.0700, 0.0000, 0.0000, 5, 12.0);

-- Mini Krakens x1 (TemplateId=54)
INSERT INTO "NpcSpawners" (TemplateId, X, Y, Z, Count, Radius) VALUES (54, 0.0000, 0.0000, -14.5400, 1, 22.0);

